#!/bin/sh -efu

BASEDIR="$(dirname $0)"

. "${BASEDIR}"/../libshell-messages

test_fail_1() {
  fail "foobar" 2>&1 > /dev/null
}

test_fail_2() {
  FAIL_WITH=5
  fail "foobar" 2>&1 > /dev/null
}

( test_fail_1 )
( test_fail_2 )
