#!/bin/sh -efu

# fail()
#
#   Produces a message and aborts program
#
#   Use `FAILWITH=X fail foobar` if you need to separate exitcodes
#
fail() {
  local __FAILWITH="${FAILWITH:-1}"

  echo "ERROR: $*" >&2
  exit "${__FAILWITH}"
}

# warning()
#
#   Produces warning message
#
warning() {
  echo "WARNING: $*" >&2
}

# verbose()
#
#   Produces a message if $VERBOSE is set
verbose() {
  [ -n "${VERBOSE}" ] && echo "VERBOSE: $*" >&2 ||:
}

# message()
#
#   Produce a message
message() {
  local PROG="${PROG:-$(basename $0)}"
  echo "$PROG: $*"
}
