#!/bin/sh -efu

__ASSERTION_HEADER="ASSERTION FAILED"

assert() {
  if [ $# -lt 3 ]; then
    echo "assert() accepts 3 or 4 parameters. The only provided were $*" >&2
    exit 1
  fi

  if [ "$2" != "$3" ]; then
    echo "${__ASSERTION_HEADER}: $1 expected: <$2> but was <$3>" >&2
    [ -n "${4:-}" ] && exit $4 ||:
  fi
}

assert_not() {
  if [ $# -lt 3 ]; then
    echo "assert_not() accepts 3 or 4 parameters. The only provided were $*" >&2
    exit 1
  fi

  if [ "$2" = "$3" ]; then
    echo "${__ASSERTION_HEADER}: $1 expected not to be <$2>" >&2
    [ -n "${4:-}" ] && exit $4 ||:
  fi
}
